# .files
# sjaks@github

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return;;
esac


# Define colors
TERRED="\[\033[0;31m\]"
TERGREEN="\[\033[0;32m\]"
TERYELLOW="\[\033[0;33m\]"
TERBLUE="\[\033[0;34m\]"
TERMAGENTA="\[\033[0;35m\]"
TERCYAN="\[\033[0;36m\]"
TERWHITE="\[\033[0;37m\]"
TERNOCOL="\[\033[0m\]"


# Enable color support for ls, grep, cat, tail and gcc
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# Set history settings
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000


# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# Allow changing directories by just typing in their names.
shopt -s autocd


# Clear temporary files. Removes some common
# cache and temp locations.
clear_cache () {
	rm -rf /home/sami/.cache/*
	rm /home/sami/.python_history
	rm /home/sami/.viminfo
	rm /home/sami/.wget-hsts
	rm /home/sami/.gnuplot_history
	rm /home/sami/.node_repl_history
	rm /home/sami/.php_history
}


# Do basic maintenance to system. Syncs repos,
# updates packages, removes some totally unnecessary
# temp files and moves Downloads and screenshots to trash.
daily () {
	cd /home/sami/.files
	git pull --rebase
	sudo update-grub
	sudo apt-get update
	sudo apt-get -y upgrade
	sudo apt-get install -f
	sudo apt-get clean
	clear_cache
	mv /home/sami/Downloads/* /home/sami/.local/share/Trash/files
	mv /home/sami/Pictures/Screenshot* /home/sami/.local/share/Trash/files
	sudo apt-get -y autoremove
	cd -
}


# Custom aliases
alias ll='echo -n "count " && ls -1A | wc -l && ls -alFh --group-directories-first'
alias neofetch='neofetch --ascii_distro GNU'
alias gitt='git log --oneline --all --graph'
alias curll='curl -IL'
alias digg='dig ANY +noall +answer'
alias digfi='dig +short all @a.fi'
alias myip='curl ipinfo.io/ip'
alias sus='sudo -E su'
alias apps='apt list --installed | grep -v automatic'
alias vagclean='docker-compose down -v --remove-orphans && rm -rf .vagrant'
alias wpup='docker-compose run -e WP_USER_UID=$UID --service-ports --rm wordpress'


# Bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

eval "$(starship init bash)"
