# .files
# sjaks@github

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return;;
esac


# Enable color support for ls, grep, cat and tail
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi


# Set history settings
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000


# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# Do basic maintenance to system. Syncs repos,
# updates packages, removes some totally unnecessary
# temp files and moves Downloads and screenshots to trash.
daily () {
	rm -rf /home/sami/.cache/*
	rm /home/sami/.python_history
	rm /home/sami/.viminfo
	rm /home/sami/.wget-hsts
	rm /home/sami/.gnuplot_history
	rm /home/sami/.node_repl_history
	rm /home/sami/.php_history
	rm /home/sami/.lesshst
	sudo dnf -y upgrade
	sudo dnf -y autoremove
}


# Custom aliases
alias ll='ls -alFh --group-directories-first'
alias gitt='git log --oneline --all --graph'
alias curll='curl -IL'
alias digg='dig ANY +noall +answer'
alias code='codium'


# Bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PS1=' \[\033[01;32m\]\w\[\033[33m\]:$(git branch 2>/dev/null | grep '^*' | colrm 1 2) \[\033[00m\]\$ '
