# .zshrc
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Vars
export ZSH="$HOME/.oh-my-zsh"
export EDITOR='pico'
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/opt/homebrew/bin:$PATH"

# ZSH settings
ZSH_THEME="af-magic"
zstyle ':omz:update' mode reminder
plugins=(git docker zsh-autosuggestions)

# Custom aliases
alias ll="ls -alFh"

# Load shell
source $ZSH/oh-my-zsh.sh
echo "Good day!"
