# Vars
export ZSH="$HOME/.oh-my-zsh"
export EDITOR='pico'
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/opt/homebrew/bin:$PATH"

# ZSH settings
ZSH_THEME="af-magic"
zstyle ':omz:update' mode reminder
plugins=(git docker)

# Custom aliases
alias ll="ls -alFh"

# Command history
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source $ZSH/oh-my-zsh.sh
